ALTER TABLE class_course AUTO_INCREMENT = 1;
INSERT INTO `class_course` (`class_id`, `title`, `description`) VALUES
(205, 'BIO 105', 'Biology - Parasitology'),
(206, 'CIE 377', 'Civil Engineering - Surveying'),
(207, 'CMPSC 130', 'Computer Sciences - Theory Of Computation : Concurrency Theory'),
(208, 'ECO 223', 'Economics - Macroeconomics'),
(209, 'ECO 339', 'Economics - Participatory Economics'),
(210, 'EE 192', 'Electrical Engineering - Control Systems Engineering : Control Theory'),
(211, 'EE 142', 'Electrical Engineering - Power Engineering'),
(212, 'KINES 384', 'Human Physical Performance And Recreation - Game Design'),
(213, 'JOUR 188', 'Journalism, Media Studies And Communication - Journalism : New Media Journalism'),
(214, 'LIN 226', 'Linguistics - Computational Linguistics / Natural Language Processing'),
(215, 'LIN 105', 'Linguistics - Sociolinguistics'),
(216, 'LIT 377', 'Literature - Creative Writing : Creative Nonfiction'),
(217, 'LIT 130', 'Literature - Creative Writing : Playwrighting'),
(218, 'PHIL 223', 'Logic - Philosophical Logic'),
(219, 'MTH 339', 'Mathematics - Algebra : Category Theory -- Topos Theory'),
(220, 'MED 192', 'Medicine - Internal Medicine : Ophthalmology'),
(221, 'MED 142', 'Medicine - Orthoptics'),
(222, 'MED 384', 'Medicine - Radiology'),
(223, 'MUS 188', 'Performing Arts - Music : Recording'),
(224, 'PHIL 226', 'Philosophy - Applied Philosophy : Philosophy Of Science -- Philosophy Of Biology'),
(225, 'PHIL 105', 'Philosophy - Metaphysics : Ontology'),
(226, 'POL 377', 'Public Administration - Police Science'),
(227, 'REL 130', 'Religion - Abrahamic Religions : Christianity -- Christian Theology'),
(228, 'REL 223', 'Religion - Indian Religions'),
(229, 'SOC 339', 'Sociology - Collective Behavior'),
(230, 'SOC 192', 'Sociology - Social Change'),
(231, 'SOC 142', 'Sociology - Sociology Of Culture'),
(232, 'STAT 384', 'Statistics - Computational Statistics'),
(233, 'SCI 188', 'Systems Science - Control Theory : Control Engineering'),
(234, 'SCI 226', 'Systems Science - Cybernetics');
