ALTER TABLE class_course AUTO_INCREMENT = 1;
INSERT INTO `class_course` (`class_id`, `title`, `description`) VALUES
(1, 'BIO 105', 'Biology - Parasitology'),
(2, 'CIE 377', 'Civil Engineering - Surveying'),
(3, 'CMPSC 130', 'Computer Sciences - Theory Of Computation : Concurrency Theory'),
(4, 'ECO 223', 'Economics - Macroeconomics'),
(5, 'ECO 339', 'Economics - Participatory Economics'),
(6, 'EE 192', 'Electrical Engineering - Control Systems Engineering : Control Theory'),
(7, 'EE 142', 'Electrical Engineering - Power Engineering'),
(8, 'KINES 384', 'Human Physical Performance And Recreation - Game Design'),
(9, 'JOUR 188', 'Journalism, Media Studies And Communication - Journalism : New Media Journalism'),
(10, 'LIN 226', 'Linguistics - Computational Linguistics / Natural Language Processing'),
(11, 'LIN 105', 'Linguistics - Sociolinguistics'),
(12, 'LIT 377', 'Literature - Creative Writing : Creative Nonfiction'),
(13, 'LIT 130', 'Literature - Creative Writing : Playwrighting'),
(14, 'PHIL 223', 'Logic - Philosophical Logic'),
(15, 'MTH 339', 'Mathematics - Algebra : Category Theory -- Topos Theory'),
(16, 'MED 192', 'Medicine - Internal Medicine : Ophthalmology'),
(17, 'MED 142', 'Medicine - Orthoptics'),
(18, 'MED 384', 'Medicine - Radiology'),
(19, 'MUS 188', 'Performing Arts - Music : Recording'),
(20, 'PHIL 226', 'Philosophy - Applied Philosophy : Philosophy Of Science -- Philosophy Of Biology'),
(21, 'PHIL 105', 'Philosophy - Metaphysics : Ontology'),
(22, 'POL 377', 'Public Administration - Police Science'),
(23, 'REL 130', 'Religion - Abrahamic Religions : Christianity -- Christian Theology'),
(24, 'REL 223', 'Religion - Indian Religions'),
(25, 'SOC 339', 'Sociology - Collective Behavior'),
(26, 'SOC 192', 'Sociology - Social Change'),
(27, 'SOC 142', 'Sociology - Sociology Of Culture'),
(28, 'STAT 384', 'Statistics - Computational Statistics'),
(29, 'SCI 188', 'Systems Science - Control Theory : Control Engineering'),
(30, 'SCI 226', 'Systems Science - Cybernetics');
