DELETE FROM question;
ALTER TABLE question AUTO_INCREMENT = 1;
INSERT INTO `question` (`question_id`, `asked`, `description`, `tags`, `potential_answers`, `correct_answers`) VALUES
(1, 0, '1 Whats your full name?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(2, 0, '2 How old are you?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(3, 0, '3 Whats your Birthday?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(4, 0, '4 What starsign does that make it?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(5, 0, '5 Whats your favourite colour?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(6, 0, '6 Whats your lucky number?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(7, 0, '7 Do you have any pets?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(8, 0, '8 Where are you from?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(9, 0, '9 How tall are you?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(10, 0, '10 What shoe size are you?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(11, 0, '11 How many pairs of shoes do you own?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(12, 0, '12 If you were prime miniser/ruler of the world what laws would you make?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(13, 0, '13 If you were a super hero what powers would you have?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(14, 0, '14 and what would your hero name be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(15, 0, '15 and what outfit would you wear?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(16, 0, '16 What was your last dream about?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(17, 0, '17 What would you do if you won the lottery?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(18, 0, '18 Would you like to build/design your own house?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(19, 0, '19 Which form of public transport do you prefer?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(20, 0, '20 What talents do you have?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(21, 0, '21 Can you juggle?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(22, 0, '22 Can you solve a rubix cube?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(23, 0, '23 Do you have a cherished childhood teddybear?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(24, 0, '24 Are you psychic in any way?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(25, 0, '25 Are you a good dancer?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(26, 0, '26 Are you a good singer?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(27, 0, '27 Are you a good cook?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(28, 0, '28 Are you a good artist?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(29, 0, '29 Are you a good listener?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(30, 0, '30 Are you a good public speaker?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(31, 0, '31 Are you a good babysitter?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(32, 0, '32 Are you a good mechanic?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(33, 0, '33 Are you a good diplomat?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(34, 0, '34 Are you a good employee?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(35, 0, '35 Are you a good dresser?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(36, 0, '36 Are you a good swimmer?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(37, 0, '37 Are you a good skier?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(38, 0, '38 Are you a good lover?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(39, 0, '39 Are you a good musician?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(40, 0, '40 Are you a good comedian?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(41, 0, '41 Are you a good cleaner?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(42, 0, '42 Are you a good actor?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(43, 0, '43 Are you a good writer?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(44, 0, '44 Have you ever been bungee jumping?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(45, 0, '45 Have you ever been canoeing/kayaking?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(46, 0, '46 What types of holidays do you prefer?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(47, 0, '47 Whats the furthest you\'ve ever been on holiday?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(48, 0, '48 What was your favourite holiday?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(49, 0, '49 Where would your dream holiday be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(50, 0, '50 Can you tap dance?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(51, 0, '51 Whats your favourite zoo animal?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(52, 0, '52 Whats your favourite sport?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(53, 0, '53 Whats your favourite food?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(54, 0, '54 Whats your favourite pizza topping?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(55, 0, '55 Whats your favourite film?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(56, 0, '56 Whats your favourite song?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(57, 0, '57 Whats your favourite alcoholic drink?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(58, 0, '58 Whats your favourite non-alcoholic drink?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(59, 0, '59 Whats your favourite TV program?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(60, 0, '60 Whats your favourite boyband?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(61, 0, '61 Whats your favourite girl group?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(62, 0, '62 What would be your ideal partner?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(63, 0, '63 Do you want children?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(64, 0, '64 Do you want a church wedding?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(65, 0, '65 Are you religious?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(66, 0, '66 Do you like reality TV programs?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(67, 0, '67 Do you like TV talent shows?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(68, 0, '68 If you were gay who would your life partner be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(69, 0, '69 If you could go back in time to change one thing what would it be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(70, 0, '70 How many hats do you own?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(71, 0, '71 Are you any good at pool?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(72, 0, '72 Whats the highest you\'ve ever jumped into the water from?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(73, 0, '73 Have you ever been admitted to hospital?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(74, 0, '74 Have you ever had any brushes with the law?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(75, 0, '75 Have you ever been on TV?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(76, 0, '76 Have you ever met any celebrities?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(77, 0, '77 Have you ever been to Legoland?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(78, 0, '78 Have you ever done something heroic?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(79, 0, '79 Have you ever played a practical joke on anyone?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(80, 0, '80 Have you ever been the recipiant of a practical joke?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(81, 0, '81 What would be your best achievement to date?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(82, 0, '82 Do you prefer baths or showers?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(83, 0, '83 Do you prefer towel drying, blow drying or natural dryin your hair?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(84, 0, '84 Have you ever built a snowman?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(85, 0, '85 Have you ever been sledging?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(86, 0, '86 Have you ever flown a kite?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(87, 0, '87 What colour socks are you wearing?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(88, 0, '88 If you could live anywhere, where would that be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(89, 0, '89 Have you ever been famous?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(90, 0, '90 Would you like to be a big celebrity?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(91, 0, '91 Would you ever go on Big Brother?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(92, 0, '92 How big is your TV?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(93, 0, '93 What is your most essential appliance?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(94, 0, '94 What type of music do you like?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(95, 0, '95 Have you ever been skinnydipping?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(96, 0, '96 How many Pillows do you sleep with?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(97, 0, '97 What position do you often sleep in?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(98, 0, '98 What do you wear to bed?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(99, 0, '99 How big is your house?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(100, 0, '100 Do you prefer sunrises or sunsets?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(101, 0, '101 What do you typically have for breakfast?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(102, 0, '102 Do you like scary movies?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(103, 0, '103 Whats your favourite Milkshake flavour?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(104, 0, '104 Have you ever been in a newspaper?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(105, 0, '105 How long can you balance on one foot?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(106, 0, '106 Have you ever fired a gun?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(107, 0, '107 Have you ever tried archery?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(108, 0, '108 Whats your favourite condement?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(109, 0, '109 Whats your favourite clean word?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(110, 0, '110 Whats your favourite swear word?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(111, 0, '111 Whats your least favourite word?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(112, 0, '112 What was the last film you saw?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(113, 0, '113 What football team do you support?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(114, 0, '114 Whats the longest you\'ve gone without sleep?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(115, 0, '115 Whats the tallest building you\'ve ever been up?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(116, 0, '116 Do you have any scars?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(117, 0, '117 Do you like marmite?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(118, 0, '118 Did you ever win any sportsday events?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(119, 0, '119 What did you want to be when you grew up?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(120, 0, '120 If you could change anything about yourself what would it be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(121, 0, '121 Whats the longest you\'ve ever grown your hair?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(122, 0, '123 Are you scared of flying?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(123, 0, '124 Would you rather trade some intelligence for looks or looks for intelligence?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(124, 0, '125 Have you ever tie-dyed your own clothes?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(125, 0, '126 How often do you buy new clothes?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(126, 0, '127 Are you reliable?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(127, 0, '128 Are you proud of yourself?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(128, 0, '129 Have you ever had a secret admirer', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(129, 0, '130 If you could ask your future self one question what would it be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(130, 0, '131 Do you hold grudges?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(131, 0, '132 If you could breed two animals together to defy the laws of nature what new animal would you create?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(132, 0, '133 Do you decorate the outside of your house for christmas?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(133, 0, '134 Can you solve sudoko puzzles?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(134, 0, '135 Have you ever played conkers?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(135, 0, '136 Whats the most unusual conversation you\'ve ever had?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(136, 0, '137 Are you much of a gambler?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(137, 0, '138 Are you much of a daredevil?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(138, 0, '139 Are you a good liar?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(139, 0, '140 Are you a good judge of character?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(140, 0, '141 Are you any good at charades?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(141, 0, '142 How long could you go without talking?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(142, 0, '143 What has been your worst haircut/style?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(143, 0, '144 Can you iceskate?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(144, 0, '145 Can you summersault?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(145, 0, '146 Whats your favourite joke?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(146, 0, '147 Whats been your best present?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(147, 0, '148 Whats been your worst present?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(148, 0, '149 Have you ever sleepwalked?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(149, 0, '150 Can you build a house of cards?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(150, 0, '151 Whats your favourite TV advert?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(151, 0, '152 Can you play poker?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(152, 0, '153 If your parents hated your partner you currently loved would you ditch him or carry on with him despite the protests?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(153, 0, '154 Have you ever been professionally photographed?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(154, 0, '155 Have you ever baked your own cake?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(155, 0, '156 Whats your favourite fruit pastel colour?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(156, 0, '157 What traditionally adorns the top of your christmas tree?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(157, 0, '158 What would be your dream sandwich?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(158, 0, '159 Can you inpersonate anyone famous?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(159, 0, '160 Can you do any accents other than your own?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(160, 0, '161 Do you have a strong local accent?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(161, 0, '162 Whats your favourite accent?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(162, 0, '163 In O\'s and X\'s which do you normally pick?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(163, 0, '164 Do you prefer blue or black inked pens?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(164, 0, '165 What was the last thing you recorded off TV?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(165, 0, '166 What was the last thing you dressed up as for fancy dress?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(166, 0, '167 Do you prefer green or red grapes?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(167, 0, '168 What do you like on your toast?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(168, 0, '169 Do you prefer liquid soap or bars of soap?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(169, 0, '170 How do you have your eggs?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(170, 0, '171 Whats your favourite saying?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(171, 0, '172 Have you ever been in a tug of war?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(172, 0, '173 and did you win?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(173, 0, '174 Can you stand on your hands unassisted?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(174, 0, '175 What do you have on your fridge door?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(175, 0, '176 Do you love or hate myspace?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(176, 0, '177 Who was the last person to knock/ring at your door?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(177, 0, '178 How old were you when you last went trick or treating?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(178, 0, '179 Have you ever been bobbing for apples?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(179, 0, '180 Whats your most expensive piece of clothing?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(180, 0, '181 Whats the last thing you took a picture of?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(181, 0, '182 Whats the last thing you drew a picture of?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(182, 0, '183 Have you ever bought anything from ebay?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(183, 0, '184 Whats your favourite smell/scent?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(184, 0, '185 Can you blow bubbles with bubblegum?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(185, 0, '186 What was your favourite birthday?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(186, 0, '187 Can you curl your tounge?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(187, 0, '188 Is your bellybutton an innie or outie?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(188, 0, '189 What would be your dream car?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(189, 0, '190 Are you left or right handed?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(190, 0, '191 What was the last book you read?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(191, 0, '192 What was the last song you danced to?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(192, 0, '193 Have you ever owned a yo-yo?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(193, 0, '194 Have you ever been on a pogo stick?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(194, 0, '195 Have you ever been on a space hopper?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(195, 0, '196 Who was the last person to send you a text message?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(196, 0, '197 Have you ever accidentally injured anyone?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(197, 0, '198 Are you scared of spiders?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(198, 0, '199 Can you down a pint of anything in one?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(199, 0, '200 Have you ever been banned from a public place?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(200, 0, '201 How much spam email do you tend to get a week?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(201, 0, '202 If you could learn any language fluently what would it be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(202, 0, '203 What historical Figure would you love to see in 21st centuary life?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(203, 0, '204 As a kid were you ever frighted of a monster under the bed or in the cupboard?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(204, 0, '205 Do you like clowns?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(205, 0, '206 Do you prefer BBC or ITV?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(206, 0, '207 Have you ever been surfing?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(207, 0, '208 Have you ever been snowboarding?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(208, 0, '209 Who was better, the Beatles or Elvis Presley?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(209, 0, '210 Whats your favourite type of foreign food?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(210, 0, '211 Which Foreign country do you dislike the most?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(211, 0, '212 Do you like your music loud or easy listening?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(212, 0, '213 Whats your favourite animated or cartoon program?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(213, 0, '214 Do you sing in the shower?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(214, 0, '215 Are you a clean or messy person?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(215, 0, '216 Whats your prefered playing piece in monopoly?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(216, 0, '217 Can or Do you still play twister?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(217, 0, '218 Can you play chess?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(218, 0, '219 Do you know the dance steps to an annoying cheesey pop song?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(219, 0, '220 Do you prefer straight or bendy straws?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(220, 0, '221 Have you ever entered a talent contest?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(221, 0, '222 and did you win?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(222, 0, '223 Do you like poetry?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(223, 0, '224 Are you a bad loser?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(224, 0, '225 Which would you choose? Jelly or Ice Cream?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(225, 0, '226 Whats your favourite type of Pie?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(226, 0, '227 Whats your most used phrase?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(227, 0, '228 Whats your most used word?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(228, 0, '229 Who would you want to play you in a movie of your life?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(229, 0, '230 What would your dream job be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(230, 0, '231 Which song do you hate the most?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(231, 0, '232 How long does it take you to get ready?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(232, 0, '233 What do you think the greatest invention has been?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(233, 0, '234 Whats your favourite feature on the opposite sex?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(234, 0, '235 Whats your least favourite feature on the opposite sex?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(235, 0, '236 Who\'s your favourite Comedian?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(236, 0, '237 What\'s your favourite board game?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(237, 0, '238 Do you have any lucky items, objects or traditions?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(238, 0, '239 Do you have any superstitions?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(239, 0, '240 Whats your favourite Movie quote?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(240, 0, '241 Who would win in a fight? Chuck Norris or Jack Bauer?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(241, 0, '242 Do you have much of an ego?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(242, 0, '243 Do you wear sunglasses indoors to look cool or stylish?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(243, 0, '244 Are you a hat person?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(244, 0, '245 Whats your favourite supermarket chain?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(245, 0, '246 Whats your favourite fastfood chain?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(246, 0, '247 Whats your first thought upon waking up?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(247, 0, '248 What animal would you most like to have as a pet?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(248, 0, '249 Whats your favourite type of tree?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(249, 0, '250 If you could bankrupt one person or company who would it be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(250, 0, '251 If you could steal one thing without consequence what would it be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(251, 0, '252 Who\'s your favourite celeb with the same first name or surname as you?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(252, 0, '253 If evil-doers invaded your country would you rush to the battlelines to defend the motherland or hide in a box?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(253, 0, '254 Whats your favourite flower?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(254, 0, '255 Do you believe in ghosts?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(255, 0, '256 Do you believe in the loch ness monster?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(256, 0, '257 Do you believe in Aliens?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(257, 0, '258 Do you believe the Governments hide technology and information from the public?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(258, 0, '259 Which is your favourite pokemon?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(259, 0, '260 What horror fiction character scares you the most?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(260, 0, '261 Can you do 10 revolutions of a hula hoop?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(261, 0, '262 Do you think Great Britain should have a National Day?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(262, 0, '263 Do you think Great Britain should be part of a United Europe?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(263, 0, '264 Would you want the Euro or keep the British Pound?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(264, 0, '265 Were you part of the Brownies/Cubs/Scouts/Guides etc', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(265, 0, '266 Have you ever invented a fairly unique meal or drink?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(266, 0, '267 Do you have any secret family recipes?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(267, 0, '268 Do you have any family secrets? :o', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(268, 0, '269 Are you good at keeping secrets?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(269, 0, '270 Have you ever been up in a hot air balloon?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(270, 0, '271 Whats your favourite Sci-fi film/program etc?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(271, 0, '272 When playing checkers or chess do you prefer to be black or white?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(272, 0, '273 Which is better, a Pastie or Sausage Roll?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(273, 0, '274 Do you prefer shopping on the high street or online?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(274, 0, '275 Would you ever want to learn to fly?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(275, 0, '276 Do you often read your horoscope?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(276, 0, '277 Have you ever had a proper Tarot reading?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(277, 0, '278 Whats your favourite brand of newspaper?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(278, 0, '279 Have you ever milked a cow?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(279, 0, '280 Have you ever used the phrase \'back in my time\' to someone younger than you?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(280, 0, '281 Do you love or hate rollercoasters?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(281, 0, '282 Which was the greatest Empire?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(282, 0, '283 Whats the cleverest word you know?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(283, 0, '284 Whats your favourite sportsware brand?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(284, 0, '285 Do you buy any weekly/monthly magazines?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(285, 0, '286 Who\'s your favourite Superhero?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(286, 0, '287 Who\'s your favourite Villain/Baddie?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(287, 0, '288 What was the last Album you purchased?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(288, 0, '289 What was the last DVD you purchased?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(289, 0, '290 What was the last piece of clothing you purchased?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(290, 0, '291 When pulling crackers does everyone get one each regardless or whoever gets the big ends keeps all the prizes', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(291, 0, '292 Do you ever make your own greetings cards', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(292, 0, '293 Do you have a swiss army knife?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(293, 0, '294 At what age did you twig onto the fact Santa wasnt real?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(294, 0, '295 Whats your favourite fruit?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(295, 0, '296 Have you ever done something really unbelivable, only to have no one around to see it?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(296, 0, '297 Do you buy from charity shops?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(297, 0, '298 Have you ever sold your services?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(298, 0, '299 Have you ever raised money for charity?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(299, 0, '300 Have you ever won a giant sized cuddly toy from a fair?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(300, 0, '301 Is the glass half full or half empty?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(301, 0, '302 Is the grass greener on the other side?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(302, 0, '303 If a tree falls in the forest and there\'s no one around to hear it does it make a noise?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(303, 0, '304 Why does it always rain on me?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(304, 0, '305 Have you ever sailed a boat?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(305, 0, '306 Do you love or loathe Harry Potter?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(306, 0, '307 Do you do your utmost for the environment?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(307, 0, '308 Do you love or loather Eurovison?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(308, 0, '309 Have you ever weilded a sword?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(309, 0, '310 If you were famous would you want a statue or a building names after you?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(310, 0, '311 Whats your favourite type of fish?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(311, 0, '312 Which do you prefer pony tails or pig tails?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(312, 0, '313 Whats the ultimate cake topping?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(313, 0, '314 Do you like marzipan?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(314, 0, '315 Whats better? Center Parks or Butlins?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(315, 0, '316 If you were in a band, what instrument/role would you play?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(316, 0, '317 Can you erect a tent?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(317, 0, '318 Do you suck or bite lollipops?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(318, 0, '319 Have you ever used the yellow pages?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(319, 0, '320 If you have an mp3 player what size is it?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(320, 0, '321 Do you still have any music on vinyl or casettes?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(321, 0, '322 Do you still have a camera that uses conventional film?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(322, 0, '323 Approximately how many DVD\'s do you have?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(323, 0, '323 Approximately how many Albums do you have?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(324, 0, '324 Do you talk to yourself?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(325, 0, '325 Do you sing to yourself?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(326, 0, '326 Do you know any identical twins?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(327, 0, '327 Have you ever given blood?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(328, 0, '328 Could you ever be a medical guineapig?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(329, 0, '329 Whats your favourite radio station?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(330, 0, '330 Whats your favourite letter of the Alphabet?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(331, 0, '331 Which is better? rollerblade or rollerskates?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(332, 0, '332 Have you ever written a love letter?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(333, 0, '333 How many valentines cards did you recieve this/last year?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(334, 0, '334 What are cooler? Dinosaurs or Dragons?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(335, 0, '335 Have you ever made your own ice lollies?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(336, 0, '336 Have you ever made your own Ice cream?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(337, 0, '337 Which forgeign language did you have to learn at school?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(338, 0, '338 and do you still remember enough to hold a conversation in that language?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(339, 0, '339 Do you know CPR?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(340, 0, '340 Do you have any swimming badges?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(341, 0, '341 Do you prefer digital or rotary/analogue clocks?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(342, 0, '342 How tall is the tallest person you know?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(343, 0, '343 Have you ever got lost in a maze?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(344, 0, '344 Have you ever been attacked by a wild animal?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(345, 0, '345 Have you ever ridden a camel?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(346, 0, '346 Whats your opinion on rats?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(347, 0, '347 Have you ever been to a gym?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(348, 0, '348 Have you ever been in a helicopter?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(349, 0, '349 Have you ever cheated at a test?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(350, 0, '350 Have you ever ridden a tractor?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(351, 0, '351 Are you a gossip?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(352, 0, '352 Have you ever cried at a film?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(353, 0, '353 When you\'re ill do you struggle on regardless or just curl up in bed as much as possible?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(354, 0, '354 Do you need to write down things to remember them?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(355, 0, '355 Do you keep a diary/journal?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(356, 0, '356 Are you scared of thunderstorms?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(357, 0, '357 Do you have any unusual fears or phobias?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(358, 0, '358 Whats your favourite disney movie?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(359, 0, '359 Have you ever slept in a caravan?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(360, 0, '360 Have you ever painted a house?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(361, 0, '361 Have you got green fingers?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(362, 0, '362 Whats the tallest tree you\'ve ever climbed?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(363, 0, '363 Have you ever dialed the talking clock?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(364, 0, '364 Do you always wear identical socks?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(365, 0, '365 Do you live by any motto or philosophy?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(366, 0, '366 Do you lick the yoghurt or desert lid?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(367, 0, '367 Do you lick the spoon clean after making something sweet?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(368, 0, '368 Do you like the sound of music? the musical/film', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(369, 0, '369 Have you ever made your own orangejuice?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(370, 0, '370 Have you ever sucked on a lemon?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(371, 0, '371 Have you ever licked a battery?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(372, 0, '372 Are you a good aim with a rubber band?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(373, 0, '373 Have you ever played golf?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(374, 0, '374 Whats the most unusual name you\'ve ever come across?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(375, 0, '375 Do you prefer to wash in the mornings or evenings?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(376, 0, '376 Have you ever danced in the rain?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(377, 0, '377 Do you like long or short hair?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(378, 0, '378 Have you ever sworn at an authority figure?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(379, 0, '379 Have you ever walked into a wall?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(380, 0, '380 Whats your favourite precious metal?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(381, 0, '381 Whats your favourite precious stone?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(382, 0, '382 Could you ever hunt your own meal?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(383, 0, '383 Have you ever read any comics?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(384, 0, '384 Where do you like to go to on a first date?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(385, 0, '385 Do you prefer vertical or horizontal stripes?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(386, 0, '386 Have you ever baked your own bread?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(387, 0, '387 Can you believe I can\'t believe its not butter is in fact not actually butter?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(388, 0, '388 Can you name all 50 American states?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(389, 0, '389 Have you ever owned a goldfish?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(390, 0, '390 What was your favourite school subject?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(391, 0, '391 What was your least favourite school subject?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(392, 0, '392 Have you ever passed wind in an embarassing situation?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(393, 0, '393 Have you ever played the bongos?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(394, 0, '394 Have you ever handled a snake?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(395, 0, '395 Have you ever assembled furniture by yourself?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(396, 0, '396 When did you last go to the beach?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(397, 0, '397 When if ever did you last go to london?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(398, 0, '398 What do you do to cool down when its hot?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(399, 0, '399 Whats the most unusual thing you\'ve ever eaten?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(400, 0, '400 Do you have a favourite mug?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(401, 0, '401 Do you know any self defence or martial arts?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(402, 0, '402 Who\'s your favourite movie action hero?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(403, 0, '403 Have you ever ridden a motorcycle?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(404, 0, '404 Do you collect anything?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(405, 0, '405 Is there anything you wished would come back into fashion?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(406, 0, '406 Do you stick to conventional fashions or like to try and be original?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(407, 0, '407 Have you ever given someone a handmade present?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(408, 0, '408 Are you introvert or extrovert?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(409, 0, '409 If you could have any feature from an animal what would you want?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(410, 0, '410 Whats your prefered swimming stroke?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(411, 0, '411 Have you ever been scuba diving?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(412, 0, '412 Have you ever had a disasterous interview?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(413, 0, '413 What makes you nervous?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(414, 0, '414 Which of the 5 senses would you say is your strongest?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(415, 0, '415 What colour are your eyes?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(416, 0, '416 Have you ever been to an Art gallery?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(417, 0, '417 Do you shout out the answers at the TV whilst watching quiz shows?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(418, 0, '418 Are you a valuable asset on a Pub Quiz team?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(419, 0, '419 Have you ever won any kind of quiz yourself?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(420, 0, '420 Do you get over-involved with TV or movie plots at times?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(421, 0, '421 Do you own any inflatable furniture?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(422, 0, '422 Whats the highest hill or mountain you\'ve ever climbed?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(423, 0, '423 Do you have a piggy bank?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(424, 0, '424 Whats the fastest you\'ve ever travelled in a car?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(425, 0, '425 Could you ever hand milk a cow?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(426, 0, '426 Do you have popcorn with a movie?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(427, 0, '427 Whats the futhest you\'ve ever got a paper airplane to fly?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(428, 0, '428 Have you ever built an igloo?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(429, 0, '429 Can you play the harmonica?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(430, 0, '430 Have you ever made a ball of twine or rubberbands?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(431, 0, '431 If given the option of having a flake in your ice cream do you always take it?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(432, 0, '432 Could you ever be a living organ donor?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(433, 0, '433 Which was your favourite science? Biology, Physics or Chemistry?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(434, 0, '434 Could you ever go out with someone just cause they\'re rich?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(435, 0, '435 Have you ever contemplated sueing someone?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]');
INSERT INTO `question` (`question_id`, `asked`, `description`, `tags`, `potential_answers`, `correct_answers`) VALUES
(436, 0, '436 Are you pretty devious?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(437, 0, '437 Have you ever had a surprise party? that was an actual surprise', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(438, 0, '438 Are you any good at giving massages?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(439, 0, '439 Whats been your worst date ever?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(440, 0, '440 Have you ever slapped somoene in public?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(441, 0, '441 Have you ever drawn on a sleeping or inebriated person?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(442, 0, '442 Have you ever warn clothing with the labels/tags still attached?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(443, 0, '443 Have you ever slipped on a banana skin?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(444, 0, '444 Are you scared of the dark?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(445, 0, '445 Do you have a lawyer?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(446, 0, '446 Have you ever been wolf whistled in public?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(447, 0, '447 Whats the worst chatup line you\'ve heard?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(448, 0, '448 Have you ever been water skiing?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(449, 0, '449 Have you ever hopelessly failed a test?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(450, 0, '450 If you had a year off, what would you want to do?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(451, 0, '451 How many sms/txt messages do you recieve on average a day?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(452, 0, '452 How long did you last phone call last?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(453, 0, '453 Do you go to car boot sales?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(454, 0, '454 If you saw someone drop a Â£10 note, would you claim it for your own or try to return it to them?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(455, 0, '455 Have you ever helped someone across the road?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(456, 0, '456 Have you ever been horseriding?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(457, 0, '457 Have you ever walked a tightrope?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(458, 0, '458 Have you ever demolished a wall or building?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(459, 0, '459 If you and a friend both wanted the same thing would you let the friend get it first?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(460, 0, '460 Have you ever argued over who should pay for something?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(461, 0, '461 Do you have any family heirlooms?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(462, 0, '462 Are you related or distantly related to anyone famous?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(463, 0, '463 Whats your favourite ocean?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(464, 0, '464 Do you correct peoples mistakes?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(465, 0, '465 Have you ever helped out an injured animal?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(466, 0, '466 Do you throw bread for the ducks?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(467, 0, '467 Do you think babies are little bundles of joy or smelly noisey things?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(468, 0, '468 Do you give money to buskers?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(469, 0, '469 Have you ever tossed your own pancake?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(470, 0, '470 Are you any good at egg and spoon races?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(471, 0, '471 Are you allergic to anything?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(472, 0, '472 Are you ticklish?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(473, 0, '473 Do you prefer tea,coffee or cocoa?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(474, 0, '474 Do you like Turkish Delight?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(475, 0, '475 Do you buy people presents to bring back when you go on holiday?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(476, 0, '476 Are you tired of answering questions yet?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(477, 0, '477 Have you ever been wheelbarrow racing?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(478, 0, '478 Do you ever forward or reply to chain mails?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(479, 0, '479 Do you often have a tune in your head you can\'t name?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(480, 0, '480 Has anyone ever approached you thinking you were someone else?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(481, 0, '481 Have you ever been approached by someone who knew you but you couldn\'t remember them for the life of you?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(482, 0, '482 What do you do to keep fit?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(483, 0, '483 Are you the sort to step in and try to break up a fight?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(484, 0, '484 Have you ever been in a fight?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(485, 0, '485 Have you ever started a rumour?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(486, 0, '486 Have you ever heard any outstanding rumours about yourself?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(487, 0, '487 Have you ever been in or had a food fight?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(488, 0, '488 When its your birthday do you always wear an age badge?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(489, 0, '489 Have you ever starred in an amateur or professional video?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(490, 0, '490 If you were comfortbly rich would you work hard for more or rest on your laurels?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(491, 0, '491 Have you ever been in a position of authority?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(492, 0, '492 Have you ever been caught in a comprimising position? even despite a valid explanation?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(493, 0, '493 Have you ever tried to make your own alcohol?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(494, 0, '494 If you were ruler of your own country what would you call it?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(495, 0, '495 And what title would you give yourself?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(496, 0, '496 If you invented a monster what would you call it?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(497, 0, '497 And what features would it have?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(498, 0, '498 Have you ever had a dream you chased only to be let down when you achived it?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(499, 0, '499 Is there anything about the opposite sex you just don\'t understand or comprehend?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(500, 0, '500 Who was your favourite teacher at school and why?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(501, 0, '501 Whats your favourite party game?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(502, 0, '502 Is it acceptable or unacceptable to smack a child as form of disapline?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(503, 0, '503 Can a hetrosexual male ever wear pink?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(504, 0, '504 Is it criminal to wear socks with sandals?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(505, 0, '505 If you were captain of a ship, what would you call it?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(506, 0, '506 If you were to join an emergency service which would it be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(507, 0, '507 If you were to join one of the armed forced which would it be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(508, 0, '508 Whats the worst thing about being your gender?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(509, 0, '509 Whats the best thing about being your gender?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(510, 0, '510 If you swapped genders for a day how would you spend it?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(511, 0, '511 If you were exiled what country would you choose as your new home?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(512, 0, '512 Have you ever made someone cry?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(513, 0, '513 Have you ever starred in a school play?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(514, 0, '514 Were you a member of any celebrity fanclub?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(515, 0, '515 Have you ever been a member of any other club?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(516, 0, '516 If you could have a full scholarship to any university what would you choose to study?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(517, 0, '517 Whats been your greatest ever day?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(518, 0, '518 What historical period would you like to live in if you could go back in time?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(519, 0, '519 What would you bring along to an idillic picnic?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(520, 0, '520 Whats your favourite childrens story?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(521, 0, '521 What movie ending really frustrated you? And how would you change it?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(522, 0, '522 What three things do you think of most each day?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(523, 0, '523 What do you call your evening meal? Dinner Tea or Supper?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(524, 0, '524 What do you call your after meal sweet? Pudding or Dessert?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(525, 0, '525 If you had a warning label, what would yours say?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(526, 0, '526 Have you ever got sweet revenge on anyone?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(527, 0, '527 Have you ever been to a live concert?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(528, 0, '528 Have you ever been to see stand up comedy?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(529, 0, '529 Have you ever needed stitches?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(530, 0, '530 If you could invent brand new baby names what would they be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(531, 0, '531 Do your dreams ever tell you to do anything?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(532, 0, '532 Who\'s your favourite radio 1 DJ?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(533, 0, '533 Whats the best way to your heart?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(534, 0, '534 Do you know your own mobile phone number off by heart?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(535, 0, '535 If you were a fashion designer, what style of clothing or accessories would you design?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(536, 0, '536 Do you ever laugh at things you shouldn\'t?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(537, 0, '537 Have you ever been in a submarine?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(538, 0, '538 Have you ever walked out of a cinema before the film was done?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(539, 0, '539 What song would you say best sums you up?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(540, 0, '540 Do you have any old friends wou wish you could meet up with again?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(541, 0, '541 Whats your favourite Nursury Rhyme?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(542, 0, '542 Do you prefer metric or imperial measurements?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(543, 0, '543 Who\'s your favourite monarch of all time?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(544, 0, '544 What was the last thing you ate?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(545, 0, '545 Whats your favourite farmyard animal?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(546, 0, '546 If you could choose one celebrity to be the father/mother of your child who would it be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(547, 0, '547 What would you do if someone proposed to you tomorrow?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(548, 0, '548 What are your 3 favourite internet sites?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(549, 0, '549 How high can you jump?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(550, 0, '550 Which fictional character do you wish was real?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(551, 0, '551 Who was your first crush?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(552, 0, '552 Whats the greatest thing about being your nationality?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(553, 0, '553 Whats the least greatest thing about being your nationality?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(554, 0, '554 Do you believe in destiny, fate or free will?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(555, 0, '555 If you could talk to one species of animal which would it be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(556, 0, '556 If you had friends round what DVD\'s would you have to watch?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(557, 0, '557 Do you like vanilla or chocolate?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(558, 0, '558 Are you a giver or a receiver?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(559, 0, '559 Do you have any enemies?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(560, 0, '560 Are you scared of needles?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(561, 0, '561 How many piercings do you have? if any', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(562, 0, '562 Have you ever got majorly lost trying to get somewhere?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(563, 0, '563 How fast can you say the alphabet?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(564, 0, '564 Do you say \'Zee\' or \'Zed\' to describe the letter Z?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(565, 0, '565 What was the last thing to make you feel happy?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(566, 0, '566 What was the last thing to make you feel angry?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(567, 0, '567 You are walking to work. There is a dog drowning in the canal on the side of the street. Your boss told you if you are late one more time you\'re fired. Do you save the dog?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(568, 0, '568 Are you the kind of friend you\'d want to have as a friend yourself?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(569, 0, '569 Do you have any questions or queries about things you\'re just to scared or embarassed to ask anyone about?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(570, 0, '570 If you were a wrestler what would your stage name be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(571, 0, '571 and what would your special move be called?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(572, 0, '572 Whats the most interesting thing you can see out of your nearest window?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(573, 0, '573 Do you think Barbie is a negative role model for young girls?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(574, 0, '574 Have you ever needed an eye test?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(575, 0, '575 Do you find yourself attractive?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(576, 0, '576 Can you roll your R\'s?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(577, 0, '577 What social class do you consider yourself or your family background to be in?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(578, 0, '578 Do you know any magic tricks?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(579, 0, '579 Whats the largest amount of money you\'ve ever won?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(580, 0, '580 Whats the largest amount of money you\'ve spent in one spree?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(581, 0, '581 Whats the largest amount of money you\'ve had to borrow off of a friend or family member', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(582, 0, '582 Have you ever been on a cable car?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(583, 0, '583 Do you prefer Honey or Jam?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(584, 0, '584 Do you prefer the French or Germans?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(585, 0, '585 How fast can you get changed?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(586, 0, '586 How fast do you type?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(587, 0, '587 How fast can you run?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(588, 0, '588 Which is better, Mario or Sonic?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(589, 0, '589 Whats your favourite biscuit to dunk?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(590, 0, '590 Which would you rather have if you had to, a broken leg or a broken arm?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(591, 0, '591 Do you read a daily newspaper?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(592, 0, '592 Do you watch the news on TV?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(593, 0, '593 Have you ever had anything published?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(594, 0, '594 Do you believe in love at first sight?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(595, 0, '595 How many remote controls do you have in your house?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(596, 0, '596 Have you ever been in a hot tub or sauna?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(597, 0, '597 Have you ever had chicken pox?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(598, 0, '598 Do you own a lava lamp?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(599, 0, '599 Are you glad these are almost over?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(600, 0, '600 On a scale of 1-10 how random would you say these are?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(601, 0, '601 What is your one major weekness?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(602, 0, '602 Whats been the best descision you\'ve made in your life so far?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(603, 0, '603 Whats been the worst descision you\'ve made in your life so far?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(604, 0, '604 What words do you always struggle to spell correctly?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(605, 0, '605 On a scale of 1-10 how happy would you say you are?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(606, 0, '606 On a scale of 1-10 how smart would you say you are?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(607, 0, '607 On a scale of 1-10 how funny would you say you are?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(608, 0, '608 On a scale of 1-10 how devious would you say you are?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(609, 0, '609 On a scale of 1-10 how awesome would you say you are?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(610, 0, '610 On a scale of 1-10 how devilsh would you say you are?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(611, 0, '611 On a scale of 1-10 how nice/caring would you say you are?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(612, 0, '612 On a scale of 1-10 how bitchy would you say you are?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(613, 0, '613 On a scale of 1-10 how polite would you say you are?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(614, 0, '614 On a scale of 1-10 how attractive would you say you are?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(615, 0, '615 If you could be any famous person who would you be and why?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(616, 0, '616 Whats your favourite animal beginning with the letter A?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(617, 0, '617 Whats your favourite item of clothing beginning with the letter B?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(618, 0, '618 Whats your favourite expleitive beginning with the letter C?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(619, 0, '619 Whats your favourite boys name beginning with the letter D?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(620, 0, '620 Whats your favourite girls name beginning with the letter E?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(621, 0, '621 Whats your favourite book beginning with the letter F?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(622, 0, '622 Whats your favourite bodypart beginning with the letter G?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(623, 0, '623 Whats your favourite musical instrument beginning with the letter H?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(624, 0, '624 Whats your favourite song beginning with the letter I?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(625, 0, '625 Whats your favourite actress beginning with the letter J?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(626, 0, '626 Whats your favourite actor beginning with the letter K?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(627, 0, '627 Whats your favourite film beginning with the letter L?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(628, 0, '628 Whats your favourite tv show beginning with the letter M?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(629, 0, '629 Whats your favourite game beginning with the letter N?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(630, 0, '630 Whats your favourite non alcoholic drink beginning with the letter O?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(631, 0, '631 Whats your favourite food beginning with the letter P?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(632, 0, '632 Whats your favourite band beginning with the letter Q?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(633, 0, '633 Whats your favourite author beginning with the letter R?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(634, 0, '634 Whats your favourite sport beginning with the letter S?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(635, 0, '635 Whats your favourite job beginning with the letter T?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(636, 0, '636 Whats your favourite mythical creature beginning with the letter U?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(637, 0, '637 Whats your favourite alcoholic drink beginning with the letter V?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(638, 0, '638 Whats your favourite cartoon character beginning with the letter W?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(639, 0, '639 Whats your favourite word beginning with the letter X?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(640, 0, '640 Whats your favourite city beginning with the letter Y?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(641, 0, '641 Whats your favourite country beginning with the letter Z?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(642, 0, '642 Do you get seasick?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(643, 0, '643 If you discovered a new species of dinosaur what would you call it?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(644, 0, '644 Do you own a paddling pool?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(645, 0, '645 What do you consider is the most important piece of furniture in a house?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(646, 0, '646 What do you consider is the most important appliance in a house?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(647, 0, '647 If you could have any celebritys hair whos would it be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(648, 0, '648 Which Celebrity do you find the most annoying?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(649, 0, '649 What potential talents do you think you might have if you worked at them?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(650, 0, '650 Who was better, Flipper, Lassie or Skippy?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(651, 0, '651 If you could be trained up in any profession of your choice by top professionals what profession would you choose?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(652, 0, '652 If someone elses child was being an annoying little runt would you go tell them off or do something about it?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(653, 0, '653 Do you believe in kharma?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(654, 0, '654 Do you believe in revenge?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(655, 0, '655 Do you believe in fairies?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(656, 0, '656 Do you believe in a god?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(657, 0, '657 Do you believe there used to be dragons?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(658, 0, '658 Who would you want to be with on a desert island?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(659, 0, '659 What\'s the worst show on television?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(660, 0, '660 Who\'s your favourite god from ancient history?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(661, 0, '661 What one device would you want to see added to a mobile phone?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(662, 0, '662 Where do you see yourself in 1 months time?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(663, 0, '663 Where do you see yourself in 1 years time?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(664, 0, '664 Where do you see yourself in 10 years time?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(665, 0, '665 What was the best thing about your old school?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(666, 0, '666 What was the worst thing about your old school?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(667, 0, '667 If you could change your name to anything what would your new name be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(668, 0, '668 Do you watch too much tv?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(669, 0, '669 Have you ever planted a tree?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(670, 0, '670 Whats the heaviest thing you can lift?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(671, 0, '671 What was the last present you recieved?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(672, 0, '672 Are your ears lobed or attached?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(673, 0, '673 How often do you wash your ears?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(674, 0, '674 Could you go out with someone who had a child from a previous relationship?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(675, 0, '675 What was your first alcoholic drink?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(676, 0, '676 What was your first job?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(677, 0, '677 What was your first car? or what would you like it to be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(678, 0, '678 What was your first mobile phone?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(679, 0, '679 What is your first proper memory?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(680, 0, '680 Who was your first teacher?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(681, 0, '681 Where did you go on your first ride on an airplane?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(682, 0, '682 Who was your first best friend?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(683, 0, '683 What was your first detention for?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(684, 0, '684 Whats your strongest voluntary muscle?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(685, 0, '685 Who was your first kiss?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(686, 0, '686 What was the first film you remember seeing at the cinema?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(687, 0, '687 What thing that you\'ve made are you most proud of?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(688, 0, '688 Could you ever be someones bodygaurd?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(689, 0, '689 Michelangelo\'s David... Masterpiece or filth?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(690, 0, '690 Do you like other people buying you clothes?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(691, 0, '691 Have you ever brought a present for someone that they hated/disliked?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(692, 0, '692 What nicknames do you have/have had?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(693, 0, '693 Did you have any pretend or imaginary friends?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(694, 0, '694 Have you ever seen a therapist/shrink?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(695, 0, '695 Have you ever carved a pumpkin?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(696, 0, '696 Would you say you are a good or bad influence to others?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(697, 0, '697 Do you prefer giving or recieving gifts/help etc', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(698, 0, '698 If you were a member of the spice girls, what would your spice handle be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(699, 0, '699 If you were to become a famous singer, what would your debut album be called?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(700, 0, '700 If you could join any music group which would you want to join?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(701, 0, '701 What do your parents do?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(702, 0, '702 If you were a giant mega monster what city would you rampage?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(703, 0, '703 Did you ever have a treehouse as a kid?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(704, 0, '704 Is your dad an embarassing dancer?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(705, 0, '705 Do you plan to vote in the next election?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(706, 0, '706 If you could replace one bodypart with a super bionic replacement what bodypart and what features would the new bionic replacement have?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(707, 0, '707 What if any unusual objects have you swallowed?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(708, 0, '708 When you buy something new do you get a desire to use/play with it even when they dont have any physical application yet?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(709, 0, '709 Did you understand the Matrix Trilogy?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(710, 0, '710 Would you rather be the fella in a movie who gets the girl or the baddie with all the good lines?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(711, 0, '711 If you were stinking rich, would you only go to places other rich people went?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(712, 0, '712 Would you rather have a mans top half and a womens bottom half or visa versa?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(713, 0, '713 Rebound relationships, good or bad?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(714, 0, '714 Have you ever owned a slinky?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(715, 0, '715 Teenage parents, good bad or indifferent?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(716, 0, '716 Whats the most expensive thing you\'ve ever broken?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(717, 0, '717 Pirate downloads, good or bad?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(718, 0, '718 Democracy, good or bad?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(719, 0, '719 Communism, good or bad?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(720, 0, '720 Have you ever been electrocuted?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(721, 0, '721 Have you ever been attacked with a creamy bakery product?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(722, 0, '722 Have you ever shawn a sheep?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(723, 0, '723 Have you ever accidentally set fire to yourself?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(724, 0, '724 Have you ever eaten a whole tube of pringles by yourself?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(725, 0, '725 Have you ever been hit on by someone of the same gender?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(726, 0, '726 The war in Iraq, good or bad?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(727, 0, '727 The war in Afganistan, good or bad?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(728, 0, '728 Have you ever appeared on youtube?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(729, 0, '729 Have you ever performed in front of a large audience?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(730, 0, '730 Have you ever eaten anything prepared by a celebrity chef?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(731, 0, '731 Have you ever been on radio?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(732, 0, '732 Did your school make a teatowel that everyone submitted to?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(733, 0, '733 What colour/style was your school tie?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(734, 0, '734 Do you have to wear glasses?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(735, 0, '735 Do you bite your nails?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(736, 0, '736 Do you prefer male or female singers voices?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(737, 0, '737 Would you rather be the worlds greatest football player or lover?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(738, 0, '738 Do you get hayfever?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(739, 0, '739 Do you have a list of things to do before your \'x\' years old?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(740, 0, '740 Do you like your age?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(741, 0, '741 Whats your favourite physical thing you like about yourself?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(742, 0, '742 Whats your least favourite physical thing you like about yourself?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(743, 0, '743 Are you proud, comfortable or ashamed of your body?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(744, 0, '744 Whats your favourite personality trait you like about yourself?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(745, 0, '745 Whats your least favourite personality trait you like about yourself?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(746, 0, '746 Do you know html?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(747, 0, '747 Have you ever flown first class?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(748, 0, '748 How many languages do you speak?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(749, 0, '749 What are better, violins or pianos?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(750, 0, '750 Whats the fastest you\'ve ever driven? as driver or passenger', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(751, 0, '751 What compulsions do you have?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(752, 0, '752 What makes you angry?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(753, 0, '753 If you could see any band, which would you like to see?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(754, 0, '754 Who would you say are more attractive, English or Europeans?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(755, 0, '755 What would you say is your favourite album of all time?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(756, 0, '756 Do you dislike hairy people?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(757, 0, '757 Are you much of an adventurer?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(758, 0, '758 Do you like your own name?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(759, 0, '759 Would you ever sign a Prenuptial agreement?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(760, 0, '760 How long has your longest ever phone call been?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(761, 0, '761 Have you ever stolen anything?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(762, 0, '762 Could you ever have an affair with a married person?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(763, 0, '763 Could you ever split up a couple for one reason or another?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(764, 0, '764 What is your family christmases like?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(765, 0, '765 Do you prefer sporty or academic members of the opposite sex?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(766, 0, '766 How much would it cost to buy your love?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(767, 0, '767 Who was your least favourite teacher at school and why?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(768, 0, '768 If you met a Genie who offered you three wishes, what would you wish for? more wishes does not count', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(769, 0, '769 Whats your current Mobile phone model and do you like it?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(770, 0, '770 How much wood could a woodchuck chuck if a woodchuck could chuck wood?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(771, 0, '771 What is your favorite color?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(772, 0, '772 What is your favorite shape?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(773, 0, '773 What is your favorite song?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(774, 0, '774 What is your favorite animal?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(775, 0, '775 What is your favorite class?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(776, 0, '776 What is your favorite band?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(777, 0, '777 What is your favorite place?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(778, 0, '778 Have you already thought about your babies names?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(779, 0, '779 Have you ever been fishing?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(780, 0, '780 Have you ever had your national flag painted on your face?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(781, 0, '781 Do you have any strange body things?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(782, 0, '782 What was the last social faux pas you made?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(783, 0, '783 What makes you nostalgic?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(784, 0, '784 Whats the scariest thing you\'ve ever done?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(785, 0, '785 What fairy tale character would you most associate with?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(786, 0, '786 How much do you tend to swear in public?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(787, 0, '787 What are your strengths?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(788, 0, '788 What are your weaknesses?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(789, 0, '789 What brand are your trainers?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(790, 0, '790 If you ruled your own country, who would you get to writer your national anthem?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(791, 0, '791 Who is the most intelligent person you know?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(792, 0, '791 Whats the craziest thing you\'ve ever done for someone?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(793, 0, '792 How did you get your name?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(794, 0, '793 Whats the best piece of advice anyone has ever given you?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(795, 0, '794 If you had to describe yourself as a flavour, what would it be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(796, 0, '795 If you had to describe yourself as a car, what would it be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(797, 0, '796 If you had to describe yourself as an animal, what would it be?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(798, 0, '797 Do you think laughing at someone elses misfortune is wrong?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(799, 0, '798 If a loved one was to serenade you, what song would you most like them to sing?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(800, 0, '799 Would you ever let your parents pick out a partner for you?', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]'),
(801, 0, '800 Have you ever tried spam? the meat product', 'someTag', '[\"Yes\", \"No\", \"Maybe\", \"42\"]', '[0, 3]');
COMMIT;
